In [15]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## carregando arquivos da classe PTL

In [16]:
df_ptl = pd.read_pickle('/content/drive/MyDrive/proj_arq_2023/dataset_matrix_ptl_kay_v3.pkl')
df_ptl

,paciente,classe,idx_na_classe,classification,lpc1,lpc2,lpc3,lpc4,lpc5,lpc6,...,minimoF2,maximoF2,rangeF2,mediaF3,desvioF3,minimoF3,maximoF3,rangeF3,slope,cpps
0,edema1,edema,1,1,-0.433838,-0.489746,-0.169067,0.121643,-0.224854,0.002323,...,1067.0,2630.0,1563.0,2792.0,391.00,2124.0,4340.0,2214.0,-10.750000,9.367188
1,edema1,edema,1,1,-0.402344,-1.291992,-0.097412,1.339844,-0.364990,-0.591309,...,1067.0,2630.0,1563.0,2792.0,391.00,2124.0,4340.0,2214.0,-10.750000,9.367188
2,edema1,edema,1,1,-0.553711,-1.194336,0.096741,1.366211,-0.639648,-0.570312,...,1067.0,2630.0,1563.0,2792.0,391.00,2124.0,4340.0,2214.0,-10.750000,9.367188
3,edema1,edema,1,1,-0.560547,-1.144531,0.071106,1.290039,-0.638184,-0.518555,...,1067.0,2630.0,1563.0,2792.0,391.00,2124.0,4340.0,2214.0,-10.750000,9.367188
4,edema1,edema,1,1,-0.569336,-1.236328,0.192993,1.388672,-0.793945,-0.551758,...,1067.0,2630.0,1563.0,2792.0,391.00,2124.0,4340.0,2214.0,-10.750000,9.367188
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13386,paralisia9,paralisia,9,1,-1.376953,-0.033478,0.190186,0.891113,-0.344238,-0.326660,...,1763.0,2708.0,944.5,3220.0,396.25,2374.0,4004.0,1630.0,0.567383,2.941406
13387,paralisia9,paralisia,9,1,-1.184570,-0.180054,0.075867,0.886719,-0.194702,-0.254150,...,1763.0,2708.0,944.5,3220.0,396.25,2374.0,4004.0,1630.0,0.567383,2.941406
13388,paralisia9,paralisia,9,1,-1.419922,0.097290,0.025085,0.940918,-0.418945,-0.173828,...,1763.0,2708.0,944.5,3220.0,396.25,2374.0,4004.0,1630.0,0.567383,2.941406
13389,paralisia9,paralisia,9,1,-1.483398,0.160522,0.186279,0.900391,-0.666016,-0.229492,...,1763.0,2708.0,944.5,3220.0,396.25,2374.0,4004.0,1630.0,0.567383,2.941406
13390,paralisia9,paralisia,9,1,-1.495117,0.174072,0.202393,0.763672,-0.478760,-0.169434,...,1763.0,2708.0,944.5,3220.0,396.25,2374.0,4004.0,1630.0,0.567383,2.941406

### Dividindo PTL em treino, validação, e teste

- treino : 70%
- validação : 10%
- teste : 20%

In [17]:
train_ptl, valid_ptl, test_ptl = \
              np.split(df_ptl.sample(frac=1, random_state=42),
                       [int(.7*len(df_ptl)), int(.8*len(df_ptl))])

In [18]:
train_ptl

,paciente,classe,idx_na_classe,classification,lpc1,lpc2,lpc3,lpc4,lpc5,lpc6,...,minimoF2,maximoF2,rangeF2,mediaF3,desvioF3,minimoF3,maximoF3,rangeF3,slope,cpps
11010,paralisia37,paralisia,37,1,-1.147461,0.482178,-0.516602,0.083313,-0.192261,0.396240,...,907.0,2442.0,1536.000,2596.0,73.43750,2462.0,2832.0,369.750,-6.500000,6.031250
5493,nodulo11,nodulo,11,1,-1.725586,0.208374,1.408203,-0.598145,-1.703125,1.757812,...,1387.0,1971.0,584.000,2402.0,359.25000,1776.0,2962.0,1186.000,-6.386719,9.406250
4015,edema40,edema,40,1,-1.743164,0.727051,-0.032074,0.544922,-1.007812,0.233032,...,1604.0,1843.0,239.125,2404.0,47.09375,2346.0,2564.0,218.375,1.273438,11.828125
2342,edema27,edema,27,1,-1.034180,-0.423340,-0.860840,1.680664,0.184570,-0.066711,...,538.0,2330.0,1792.000,2390.0,332.50000,1970.0,2948.0,978.000,-12.070312,10.789062
6081,nodulo15,nodulo,15,1,-1.439453,0.871094,-1.149414,1.079102,-1.158203,1.562500,...,1047.0,1282.0,234.375,2676.0,28.78125,2566.0,2778.0,211.250,-17.734375,13.679688
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
205,edema11,edema,11,1,-1.360352,0.810547,-0.262451,-0.428223,0.967285,-0.915039,...,1848.0,2026.0,177.875,2754.0,64.31250,2568.0,2854.0,287.500,0.895508,5.035156
9327,paralisia24,paralisia,24,1,-0.732422,0.838379,-1.094727,0.804688,-1.241211,0.821777,...,1886.0,2840.0,954.500,2974.0,344.25000,2578.0,3930.0,1352.000,2.615234,4.296875
6680,nodulo3,nodulo,3,1,-1.272461,-0.531738,0.990723,0.165405,-0.652832,0.156250,...,1324.0,1533.0,209.125,2382.0,86.18750,2250.0,2580.0,330.500,-8.062500,11.757812
2749,edema30,edema,30,1,-1.134766,-0.104675,-0.384521,0.565430,0.086182,0.395020,...,1051.0,1786.0,735.000,2378.0,232.87500,1759.0,2726.0,968.000,-6.996094,12.687500
8497,paralisia18,paralisia,18,1,-1.337891,0.602051,-0.632324,0.458008,-0.911621,1.077148,...,915.0,1609.0,694.500,2808.0,198.50000,2168.0,3354.0,1186.000,-25.062500,11.976562

In [19]:
valid_ptl

,paciente,classe,idx_na_classe,classification,lpc1,lpc2,lpc3,lpc4,lpc5,lpc6,...,minimoF2,maximoF2,rangeF2,mediaF3,desvioF3,minimoF3,maximoF3,rangeF3,slope,cpps
1849,edema23,edema,23,1,-1.288086,-0.179321,-0.119751,1.154297,-0.569824,-0.110474,...,1106.0,2608.0,1502.0000,2600.0,68.500000,2502.0,3034.0,531.00,-13.984375,13.296875
12139,paralisia46,paralisia,46,1,-0.600098,-1.043945,-0.227417,0.672363,0.877441,0.022171,...,1009.5,2322.0,1312.0000,2694.0,276.500000,2126.0,3712.0,1587.00,-12.875000,11.562500
3240,edema34,edema,34,1,-0.934570,0.993164,-1.118164,0.808594,-1.083984,0.696289,...,975.0,2348.0,1373.0000,3764.0,295.000000,2330.0,4208.0,1877.00,-22.031250,8.804688
10631,paralisia33,paralisia,33,1,-1.610352,0.308838,0.241089,0.778809,-1.420898,0.850098,...,1586.0,1692.0,105.3125,2722.0,42.468750,2634.0,2846.0,212.75,-5.351562,9.476562
3109,edema34,edema,34,1,-1.148438,1.512695,-1.758789,1.567383,-1.835938,1.523438,...,975.0,2348.0,1373.0000,3764.0,295.000000,2330.0,4208.0,1877.00,-22.031250,8.804688
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5510,nodulo12,nodulo,12,1,-1.715820,1.736328,-2.453125,2.335938,-2.326172,2.720703,...,1062.0,1249.0,186.3750,2674.0,112.875000,2388.0,3190.0,803.00,-15.492188,14.382812
5330,nodulo10,nodulo,10,1,-1.468750,1.164062,-1.381836,0.713379,-0.831543,1.682617,...,785.5,2742.0,1956.0000,2902.0,255.875000,2078.0,3542.0,1464.00,-20.250000,9.125000
4531,edema44,edema,44,1,-1.239258,-0.338623,0.265869,0.765137,-0.779297,0.446289,...,1702.0,1910.0,207.8750,2716.0,187.625000,2304.0,3318.0,1012.50,-22.375000,11.289062
9866,paralisia28,paralisia,28,1,-0.983887,0.281006,-0.828125,0.510742,-0.529297,1.038086,...,1059.0,1226.0,166.8750,2642.0,49.125000,2522.0,2794.0,272.50,-17.937500,9.476562
365,edema12,edema,12,1,-1.134766,0.191406,-0.908203,0.246826,-0.047211,1.641602,...,992.0,1068.0,75.8750,2400.0,16.796875,2364.0,2442.0,77.50,-23.078125,13.523438

In [20]:
test_ptl

,paciente,classe,idx_na_classe,classification,lpc1,lpc2,lpc3,lpc4,lpc5,lpc6,...,minimoF2,maximoF2,rangeF2,mediaF3,desvioF3,minimoF3,maximoF3,rangeF3,slope,cpps
10830,paralisia35,paralisia,35,1,-1.307617,0.520508,-0.285156,-0.068298,-0.146118,0.328125,...,1728.0,1983.0,255.1250,2580.0,40.8125,2428.0,2654.0,225.75,-4.566406,6.789062
13368,paralisia9,paralisia,9,1,-1.408203,-0.025177,0.145996,1.045898,-0.509766,-0.191650,...,1763.0,2708.0,944.5000,3220.0,396.2500,2374.0,4004.0,1630.00,0.567383,2.941406
147,edema10,edema,10,1,-0.353760,-0.278076,-0.300781,0.373291,0.122803,0.065979,...,1892.0,2622.0,729.5000,2758.0,116.1250,2570.0,2994.0,423.50,-2.394531,2.574219
1668,edema22,edema,22,1,-1.499023,1.121094,-1.052734,0.618164,-0.847656,1.200195,...,1074.0,1348.0,274.0000,2878.0,70.4375,2714.0,3132.0,417.25,-14.812500,6.417969
11841,paralisia43,paralisia,43,1,-1.174805,0.116211,-0.025818,0.151611,-0.284668,0.501465,...,1428.0,2796.0,1369.0000,2902.0,209.8750,2580.0,3804.0,1223.00,0.044434,6.601562
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11964,paralisia44,paralisia,44,1,-1.057617,0.106018,-0.521484,0.584473,-0.058990,0.274658,...,1567.0,2250.0,683.5000,2362.0,145.3750,2092.0,3062.0,971.00,-7.253906,6.878906
5191,nodulo1,nodulo,1,1,-1.823242,0.687012,0.406006,-0.249512,-0.746094,1.187500,...,1544.0,1670.0,126.3125,2414.0,125.5625,1644.0,2540.0,897.00,-2.830078,11.921875
5390,nodulo10,nodulo,10,1,-1.194336,0.646973,-0.992188,0.319336,-0.704590,1.610352,...,785.5,2742.0,1956.0000,2902.0,255.8750,2078.0,3542.0,1464.00,-20.250000,9.125000
860,edema16,edema,16,1,-1.297852,-0.236572,0.184814,0.707031,-0.241211,-0.044098,...,1566.0,1691.0,125.3125,2704.0,68.4375,2524.0,2872.0,348.00,-11.390625,10.796875
7270,nodulo8,nodulo,8,1,-1.124023,-0.155518,-0.330078,0.818848,-0.236450,0.289795,...,661.0,2336.0,1675.0000,2288.0,240.5000,1590.0,3038.0,1448.00,-7.984375,8.921875

In [21]:
print("checando divisão PTL:")
print(r"PTL - Treino: {:.2f}%".format((len(train_ptl) / len(df_ptl))*100))
print(r"PTL - Validação: {:.2f}%".format((len(valid_ptl) / len(df_ptl))*100))
print(r"PTL - Teste: {:.2f}%".format((len(test_ptl) / len(df_ptl))*100))

checando divisão PTL:
PTL - Treino: 69.99%
PTL - Validação: 10.00%
PTL - Teste: 20.01%

## carregando dados SDL

In [22]:
df_sdl = pd.read_pickle('/content/drive/MyDrive/proj_arq_2023/dataset_matrix_sdl_kay_v3.pkl')
df_sdl

,paciente,classe,idx_na_classe,classification,lpc1,lpc2,lpc3,lpc4,lpc5,lpc6,...,minimoF2,maximoF2,rangeF2,mediaF3,desvioF3,minimoF3,maximoF3,rangeF3,slope,cpps
0,normal1,normal,1,0,-2.132812,0.897949,0.840820,-0.446533,0.089355,-0.634766,...,1277.0,1971.0,693.5000,2348.0,30.328125,2276.0,2540.0,264.500,3.003906,12.265625
1,normal1,normal,1,0,-2.064453,0.603516,1.153320,-0.360352,-0.085693,-0.751953,...,1277.0,1971.0,693.5000,2348.0,30.328125,2276.0,2540.0,264.500,3.003906,12.265625
2,normal1,normal,1,0,-1.978516,0.454590,1.179688,-0.307861,-0.135864,-0.570312,...,1277.0,1971.0,693.5000,2348.0,30.328125,2276.0,2540.0,264.500,3.003906,12.265625
3,normal1,normal,1,0,-2.011719,0.465820,1.436523,-0.747070,-0.102905,-0.173706,...,1277.0,1971.0,693.5000,2348.0,30.328125,2276.0,2540.0,264.500,3.003906,12.265625
4,normal1,normal,1,0,-2.050781,0.627441,1.249023,-0.835449,0.216431,-0.296875,...,1277.0,1971.0,693.5000,2348.0,30.328125,2276.0,2540.0,264.500,3.003906,12.265625
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15188,normal9,normal,9,0,-2.039062,1.610352,-1.037109,0.843262,-0.237427,-0.392822,...,1717.0,1790.0,73.5625,2518.0,10.507812,2494.0,2546.0,51.625,5.808594,12.867188
15189,normal9,normal,9,0,-1.884766,1.215820,-0.609863,0.528809,0.033813,-0.604004,...,1717.0,1790.0,73.5625,2518.0,10.507812,2494.0,2546.0,51.625,5.808594,12.867188
15190,normal9,normal,9,0,-1.954102,1.412109,-0.931641,0.916016,-0.224243,-0.649414,...,1717.0,1790.0,73.5625,2518.0,10.507812,2494.0,2546.0,51.625,5.808594,12.867188
15191,normal9,normal,9,0,-2.044922,1.632812,-1.055664,0.791016,-0.125854,-0.440674,...,1717.0,1790.0,73.5625,2518.0,10.507812,2494.0,2546.0,51.625,5.808594,12.867188
15192,normal9,normal,9,0,-1.999023,1.503906,-0.928711,0.821289,-0.253174,-0.490967,...,1717.0,1790.0,73.5625,2518.0,10.507812,2494.0,2546.0,51.625,5.808594,12.867188

### dividindo dados SDL em treino, validação e teste

- treino : 70%
- validação : 10%
- teste : 20%

In [23]:
train_sdl, valid_sdl, test_sdl = \
              np.split(df_sdl.sample(frac=1, random_state=42),
                       [int(.7*len(df_sdl)), int(.8*len(df_sdl))])

In [24]:
train_sdl

,paciente,classe,idx_na_classe,classification,lpc1,lpc2,lpc3,lpc4,lpc5,lpc6,...,minimoF2,maximoF2,rangeF2,mediaF3,desvioF3,minimoF3,maximoF3,rangeF3,slope,cpps
8526,normal36,normal,36,0,-1.796875,0.416748,0.719727,0.298096,-0.775391,-0.076965,...,1836.0,2062.0,225.12500,2760.0,101.062500,2570.0,3012.0,441.25000,8.281250,13.820312
6685,normal30,normal,30,0,-2.410156,1.987305,-0.441650,0.061615,-0.281494,-0.600586,...,1608.0,1789.0,181.12500,2372.0,12.578125,2342.0,2396.0,53.84375,4.867188,11.929688
7399,normal32,normal,32,0,-2.275391,1.236328,1.211914,-1.510742,-0.356445,0.882324,...,1445.0,1845.0,399.25000,2332.0,14.234375,2308.0,2370.0,61.78125,0.688477,17.187500
14607,normal7,normal,7,0,-1.647461,0.148804,0.684570,0.186523,-0.426758,0.147095,...,1268.0,1726.0,458.50000,2172.0,84.812500,1925.0,2360.0,434.50000,0.390137,14.070312
9906,normal40,normal,40,0,-2.218750,1.313477,0.548340,-0.727539,-0.060699,-0.589355,...,1698.0,1754.0,55.90625,2206.0,12.398438,2182.0,2240.0,57.43750,3.406250,13.375000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14684,normal8,normal,8,0,-1.808594,0.912598,0.161621,-0.753906,0.953125,-0.675293,...,1744.0,2120.0,376.25000,2620.0,121.937500,2056.0,2812.0,756.00000,0.012909,18.062500
12828,normal5,normal,5,0,-1.334961,-0.377686,0.429688,0.448975,0.498291,-0.624023,...,1347.0,1395.0,47.75000,2478.0,39.812500,2376.0,2544.0,167.25000,-5.250000,13.664062
8891,normal38,normal,38,0,-1.852539,1.486328,-1.077148,0.215454,0.602539,-0.676758,...,1667.0,1740.0,72.18750,2556.0,18.687500,2514.0,2620.0,105.43750,8.015625,12.195312
3832,normal21,normal,21,0,-1.248047,-0.587891,0.846191,0.195068,-0.023315,-0.054932,...,1239.0,1916.0,677.00000,2416.0,199.375000,1713.0,2622.0,909.50000,5.679688,12.367188
13242,normal51,normal,51,0,-1.866211,0.885742,0.638672,-1.013672,0.360596,-0.349609,...,1641.0,1743.0,101.56250,2198.0,164.375000,1795.0,2870.0,1076.00000,-9.210938,21.468750

In [25]:
valid_sdl

,paciente,classe,idx_na_classe,classification,lpc1,lpc2,lpc3,lpc4,lpc5,lpc6,...,minimoF2,maximoF2,rangeF2,mediaF3,desvioF3,minimoF3,maximoF3,rangeF3,slope,cpps
4776,normal24,normal,24,0,-2.027344,1.218750,0.342285,-0.970703,1.268555,-1.385742,...,1574.0,2646.0,1072.0000,2652.0,274.50000,2396.0,3856.0,1460.000,7.148438,14.656250
7997,normal34,normal,34,0,-2.259766,1.353516,0.455322,-0.944336,0.828125,-0.691895,...,938.5,2200.0,1261.0000,2880.0,577.00000,1784.0,4700.0,2914.000,-7.972656,16.953125
4276,normal23,normal,23,0,-2.009766,0.941406,0.520996,-0.154419,-0.557617,0.246216,...,1635.0,2116.0,480.5000,2652.0,151.87500,2438.0,3140.0,700.500,6.957031,13.078125
14812,normal8,normal,8,0,-1.876953,1.071289,-0.115662,-0.336182,0.623047,-0.677734,...,1744.0,2120.0,376.2500,2620.0,121.93750,2056.0,2812.0,756.000,0.012909,18.062500
10780,normal43,normal,43,0,-1.947266,1.073242,-0.019073,0.221436,-0.100891,-0.851074,...,1724.0,1871.0,146.6250,1988.0,84.56250,1844.0,2256.0,412.500,-4.574219,21.734375
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13449,normal52,normal,52,0,-1.791016,1.362305,-1.022461,0.637207,-0.298096,0.461670,...,1809.0,1951.0,142.0000,2338.0,22.62500,2306.0,2436.0,128.875,0.680176,13.218750
7650,normal33,normal,33,0,-2.001953,0.396973,2.091797,-2.062500,0.273926,0.950195,...,1711.0,2356.0,645.0000,2374.0,110.37500,2230.0,2830.0,600.000,9.382812,13.203125
8599,normal37,normal,37,0,-1.566406,-0.222778,1.078125,-0.158447,0.251221,-0.414307,...,1214.0,1396.0,181.6250,2037.0,44.40625,1943.0,2144.0,200.875,-10.351562,12.226562
11698,normal46,normal,46,0,-1.059570,-0.618164,-0.042236,0.670410,0.803223,-0.053650,...,1547.0,1643.0,95.6875,2270.0,55.34375,2146.0,2384.0,238.750,-0.662109,11.289062
7788,normal34,normal,34,0,-2.380859,2.041016,-0.563477,-0.566406,1.404297,-1.929688,...,938.5,2200.0,1261.0000,2880.0,577.00000,1784.0,4700.0,2914.000,-7.972656,16.953125

In [26]:
test_sdl

,paciente,classe,idx_na_classe,classification,lpc1,lpc2,lpc3,lpc4,lpc5,lpc6,...,minimoF2,maximoF2,rangeF2,mediaF3,desvioF3,minimoF3,maximoF3,rangeF3,slope,cpps
3456,normal20,normal,20,0,-2.722656,2.458984,-0.347412,0.040131,-1.498047,1.240234,...,1603.0,1830.0,227.3750,2578.0,27.015625,2512.0,2726.0,213.87500,7.191406,13.367188
11768,normal47,normal,47,0,-2.320312,1.642578,0.280518,-0.875977,0.140747,0.436279,...,1099.0,2524.0,1425.0000,2456.0,347.000000,2017.0,3370.0,1353.00000,4.253906,12.109375
3271,normal2,normal,2,0,-2.316406,1.840820,0.163452,-1.379883,0.697754,0.068970,...,1269.0,2034.0,765.5000,2070.0,48.500000,1937.0,2200.0,263.50000,0.663086,17.562500
4940,normal25,normal,25,0,-2.191406,1.541992,-0.390869,0.258301,0.239136,-1.196289,...,1366.0,1988.0,622.5000,1923.0,38.187500,1894.0,2338.0,444.75000,-2.378906,20.015625
9223,normal39,normal,39,0,-2.275391,1.563477,-0.027924,0.013855,-0.475342,0.074402,...,1978.0,2068.0,91.3125,2600.0,167.125000,2138.0,3040.0,903.00000,0.963379,21.359375
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5191,normal26,normal,26,0,-1.770508,0.050934,1.272461,-0.009956,-0.727539,0.152344,...,1688.0,2012.0,324.0000,2512.0,133.750000,2005.0,2690.0,686.00000,8.875000,15.359375
13418,normal51,normal,51,0,-1.967773,1.317383,-0.179565,-0.339111,0.201904,-0.529297,...,1641.0,1743.0,101.5625,2198.0,164.375000,1795.0,2870.0,1076.00000,-9.210938,21.468750
5390,normal27,normal,27,0,-2.142578,1.186523,-0.145386,0.812988,-0.796387,0.250977,...,1520.0,2340.0,819.5000,2676.0,430.750000,2126.0,3368.0,1242.00000,7.054688,13.429688
860,normal11,normal,11,0,-1.921875,0.875977,0.339844,-0.581543,0.896484,-1.089844,...,1042.0,2360.0,1319.0000,2330.0,349.500000,2037.0,3670.0,1634.00000,-2.548828,14.539062
7270,normal32,normal,32,0,-2.572266,2.062500,0.556641,-1.826172,0.403564,0.856934,...,1445.0,1845.0,399.2500,2332.0,14.234375,2308.0,2370.0,61.78125,0.688477,17.187500

In [27]:
print("checando divisão SDL:")
print(r"SDL - Treino: {:.2f}%".format((len(train_sdl) / len(df_sdl))*100))
print(r"SDL - Validação: {:.2f}%".format((len(valid_sdl) / len(df_sdl))*100))
print(r"SDL - Teste: {:.2f}%".format((len(test_sdl) / len(df_sdl))*100))

checando divisão SDL:
SDL - Treino: 70.00%
SDL - Validação: 10.00%
SDL - Teste: 20.00%

### juntando PTL e SDL nos dados de treino, validação e teste

In [29]:
df_train_all = pd.concat([train_sdl,train_ptl])
df_train_all

,paciente,classe,idx_na_classe,classification,lpc1,lpc2,lpc3,lpc4,lpc5,lpc6,...,minimoF2,maximoF2,rangeF2,mediaF3,desvioF3,minimoF3,maximoF3,rangeF3,slope,cpps
8526,normal36,normal,36,0,-1.796875,0.416748,0.719727,0.298096,-0.775391,-0.076965,...,1836.0,2062.0,225.12500,2760.0,101.062500,2570.0,3012.0,441.25000,8.281250,13.820312
6685,normal30,normal,30,0,-2.410156,1.987305,-0.441650,0.061615,-0.281494,-0.600586,...,1608.0,1789.0,181.12500,2372.0,12.578125,2342.0,2396.0,53.84375,4.867188,11.929688
7399,normal32,normal,32,0,-2.275391,1.236328,1.211914,-1.510742,-0.356445,0.882324,...,1445.0,1845.0,399.25000,2332.0,14.234375,2308.0,2370.0,61.78125,0.688477,17.187500
14607,normal7,normal,7,0,-1.647461,0.148804,0.684570,0.186523,-0.426758,0.147095,...,1268.0,1726.0,458.50000,2172.0,84.812500,1925.0,2360.0,434.50000,0.390137,14.070312
9906,normal40,normal,40,0,-2.218750,1.313477,0.548340,-0.727539,-0.060699,-0.589355,...,1698.0,1754.0,55.90625,2206.0,12.398438,2182.0,2240.0,57.43750,3.406250,13.375000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
205,edema11,edema,11,1,-1.360352,0.810547,-0.262451,-0.428223,0.967285,-0.915039,...,1848.0,2026.0,177.87500,2754.0,64.312500,2568.0,2854.0,287.50000,0.895508,5.035156
9327,paralisia24,paralisia,24,1,-0.732422,0.838379,-1.094727,0.804688,-1.241211,0.821777,...,1886.0,2840.0,954.50000,2974.0,344.250000,2578.0,3930.0,1352.00000,2.615234,4.296875
6680,nodulo3,nodulo,3,1,-1.272461,-0.531738,0.990723,0.165405,-0.652832,0.156250,...,1324.0,1533.0,209.12500,2382.0,86.187500,2250.0,2580.0,330.50000,-8.062500,11.757812
2749,edema30,edema,30,1,-1.134766,-0.104675,-0.384521,0.565430,0.086182,0.395020,...,1051.0,1786.0,735.00000,2378.0,232.875000,1759.0,2726.0,968.00000,-6.996094,12.687500
8497,paralisia18,paralisia,18,1,-1.337891,0.602051,-0.632324,0.458008,-0.911621,1.077148,...,915.0,1609.0,694.50000,2808.0,198.500000,2168.0,3354.0,1186.00000,-25.062500,11.976562

In [30]:
len(train_sdl) + len(train_ptl)

20008

In [31]:
df_train_all.to_pickle('/content/drive/MyDrive/proj_arq_2023/train_kay_v1.pkl')

In [32]:
df_valid_all = pd.concat([valid_sdl,valid_ptl])
df_valid_all

,paciente,classe,idx_na_classe,classification,lpc1,lpc2,lpc3,lpc4,lpc5,lpc6,...,minimoF2,maximoF2,rangeF2,mediaF3,desvioF3,minimoF3,maximoF3,rangeF3,slope,cpps
4776,normal24,normal,24,0,-2.027344,1.218750,0.342285,-0.970703,1.268555,-1.385742,...,1574.0,2646.0,1072.000,2652.0,274.500000,2396.0,3856.0,1460.0,7.148438,14.656250
7997,normal34,normal,34,0,-2.259766,1.353516,0.455322,-0.944336,0.828125,-0.691895,...,938.5,2200.0,1261.000,2880.0,577.000000,1784.0,4700.0,2914.0,-7.972656,16.953125
4276,normal23,normal,23,0,-2.009766,0.941406,0.520996,-0.154419,-0.557617,0.246216,...,1635.0,2116.0,480.500,2652.0,151.875000,2438.0,3140.0,700.5,6.957031,13.078125
14812,normal8,normal,8,0,-1.876953,1.071289,-0.115662,-0.336182,0.623047,-0.677734,...,1744.0,2120.0,376.250,2620.0,121.937500,2056.0,2812.0,756.0,0.012909,18.062500
10780,normal43,normal,43,0,-1.947266,1.073242,-0.019073,0.221436,-0.100891,-0.851074,...,1724.0,1871.0,146.625,1988.0,84.562500,1844.0,2256.0,412.5,-4.574219,21.734375
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5510,nodulo12,nodulo,12,1,-1.715820,1.736328,-2.453125,2.335938,-2.326172,2.720703,...,1062.0,1249.0,186.375,2674.0,112.875000,2388.0,3190.0,803.0,-15.492188,14.382812
5330,nodulo10,nodulo,10,1,-1.468750,1.164062,-1.381836,0.713379,-0.831543,1.682617,...,785.5,2742.0,1956.000,2902.0,255.875000,2078.0,3542.0,1464.0,-20.250000,9.125000
4531,edema44,edema,44,1,-1.239258,-0.338623,0.265869,0.765137,-0.779297,0.446289,...,1702.0,1910.0,207.875,2716.0,187.625000,2304.0,3318.0,1012.5,-22.375000,11.289062
9866,paralisia28,paralisia,28,1,-0.983887,0.281006,-0.828125,0.510742,-0.529297,1.038086,...,1059.0,1226.0,166.875,2642.0,49.125000,2522.0,2794.0,272.5,-17.937500,9.476562
365,edema12,edema,12,1,-1.134766,0.191406,-0.908203,0.246826,-0.047211,1.641602,...,992.0,1068.0,75.875,2400.0,16.796875,2364.0,2442.0,77.5,-23.078125,13.523438

In [33]:
len(valid_sdl) + len(valid_ptl)

2858

In [34]:
df_valid_all.to_pickle('/content/drive/MyDrive/proj_arq_2023/valid_kay_v1.pkl')

In [35]:
df_test_all = pd.concat([test_sdl,test_ptl])
df_test_all

,paciente,classe,idx_na_classe,classification,lpc1,lpc2,lpc3,lpc4,lpc5,lpc6,...,minimoF2,maximoF2,rangeF2,mediaF3,desvioF3,minimoF3,maximoF3,rangeF3,slope,cpps
3456,normal20,normal,20,0,-2.722656,2.458984,-0.347412,0.040131,-1.498047,1.240234,...,1603.0,1830.0,227.3750,2578.0,27.015625,2512.0,2726.0,213.875,7.191406,13.367188
11768,normal47,normal,47,0,-2.320312,1.642578,0.280518,-0.875977,0.140747,0.436279,...,1099.0,2524.0,1425.0000,2456.0,347.000000,2017.0,3370.0,1353.000,4.253906,12.109375
3271,normal2,normal,2,0,-2.316406,1.840820,0.163452,-1.379883,0.697754,0.068970,...,1269.0,2034.0,765.5000,2070.0,48.500000,1937.0,2200.0,263.500,0.663086,17.562500
4940,normal25,normal,25,0,-2.191406,1.541992,-0.390869,0.258301,0.239136,-1.196289,...,1366.0,1988.0,622.5000,1923.0,38.187500,1894.0,2338.0,444.750,-2.378906,20.015625
9223,normal39,normal,39,0,-2.275391,1.563477,-0.027924,0.013855,-0.475342,0.074402,...,1978.0,2068.0,91.3125,2600.0,167.125000,2138.0,3040.0,903.000,0.963379,21.359375
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11964,paralisia44,paralisia,44,1,-1.057617,0.106018,-0.521484,0.584473,-0.058990,0.274658,...,1567.0,2250.0,683.5000,2362.0,145.375000,2092.0,3062.0,971.000,-7.253906,6.878906
5191,nodulo1,nodulo,1,1,-1.823242,0.687012,0.406006,-0.249512,-0.746094,1.187500,...,1544.0,1670.0,126.3125,2414.0,125.562500,1644.0,2540.0,897.000,-2.830078,11.921875
5390,nodulo10,nodulo,10,1,-1.194336,0.646973,-0.992188,0.319336,-0.704590,1.610352,...,785.5,2742.0,1956.0000,2902.0,255.875000,2078.0,3542.0,1464.000,-20.250000,9.125000
860,edema16,edema,16,1,-1.297852,-0.236572,0.184814,0.707031,-0.241211,-0.044098,...,1566.0,1691.0,125.3125,2704.0,68.437500,2524.0,2872.0,348.000,-11.390625,10.796875
7270,nodulo8,nodulo,8,1,-1.124023,-0.155518,-0.330078,0.818848,-0.236450,0.289795,...,661.0,2336.0,1675.0000,2288.0,240.500000,1590.0,3038.0,1448.000,-7.984375,8.921875

In [36]:
len(test_sdl) + len(test_ptl)

5718

In [37]:
df_test_all.to_pickle('/content/drive/MyDrive/proj_arq_2023/test_kay_v1.pkl')